/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifdef RADIUS /* only if RADIUS-enabled build */

#ifndef RADIUSSTATSTABLE_H
#define RADIUSSTATSTABLE_H

/* function declarations */
void init_radiusStatsTable(void);
void initialize_table_radiusStatsTable(void);
Netsnmp_Node_Handler radiusStatsTable_handler;
Netsnmp_First_Data_Point  radiusStatsTable_get_first_data_point;
Netsnmp_Next_Data_Point   radiusStatsTable_get_next_data_point;
NetsnmpCacheLoad radiusStatsTable_load;
NetsnmpCacheFree radiusStatsTable_free;
#define RADIUSSTATSTABLE_TIMEOUT  60

/* column number definitions for table radiusStatsTable */
       #define COLUMN_RADID		1
       #define COLUMN_RADADDRESS		2
       #define COLUMN_RADPORTAUTH		3
       #define COLUMN_RADPORTACCT		4
       #define COLUMN_RADQUEUECOUNT		5
       #define COLUMN_RADFAILCOUNT		6
       #define COLUMN_RADAUTHSENT		7
       #define COLUMN_RADAUTHLOST		8
       #define COLUMN_RADACCTSENT		9
       #define COLUMN_RADACCTLOST		10
       #define COLUMN_RADINTERSENT		11
       #define COLUMN_RADINTERLOST		12
       #define COLUMN_RADAUTHLOST1M		13
       #define COLUMN_RADAUTHLOST5M		14
       #define COLUMN_RADACCTLOST1M		15
       #define COLUMN_RADACCTLOST5M		16
       #define COLUMN_RADINTERLOST1M		17
       #define COLUMN_RADINTERLOST5M		18
       #define COLUMN_RADAUTHTIME1M		19
       #define COLUMN_RADAUTHTIME5M		20
       #define COLUMN_RADACCTTIME1M		21
       #define COLUMN_RADACCTTIME5M		22
       #define COLUMN_RADINTERTIME1M		23
       #define COLUMN_RADINTERTIME5M		24
#endif /* RADIUSSTATSTABLE_H */

#endif /* RADIUS */
