/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#ifdef RADIUS /* only if RADIUS-enabled build */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "radiusStatsTable.h"
#include "triton.h"
#include "radius.h"
#include "utils.h"
#include "memdebug.h"

/** Initializes the radiusStatsTable module */
void
init_radiusStatsTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_radiusStatsTable();
}

/*  # Determine the first/last column names */

/** Initialize the radiusStatsTable table by defining its contents and how it's structured */
void
initialize_table_radiusStatsTable(void)
{
    const oid radiusStatsTable_oid[] = {1,3,6,1,4,1,8072,100,1,6,1};
    const size_t radiusStatsTable_oid_len   = OID_LENGTH(radiusStatsTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("radiusStatsTable:init", "initializing table radiusStatsTable\n"));

    reg = netsnmp_create_handler_registration(
              "radiusStatsTable",     radiusStatsTable_handler,
              radiusStatsTable_oid, radiusStatsTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_OCTET_STR,  /* index: radID */
                           0);
    table_info->min_column = COLUMN_RADID;
    table_info->max_column = COLUMN_RADINTERTIME5M;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = radiusStatsTable_get_first_data_point;
    iinfo->get_next_data_point  = radiusStatsTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(RADIUSSTATSTABLE_TIMEOUT,
                                  radiusStatsTable_load, radiusStatsTable_free,
                                  radiusStatsTable_oid, radiusStatsTable_oid_len),
            TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct radiusStatsTable_entry {
    /* Index values */
    char radID[16];
    size_t radID_len;

    /* Column values */
    char radAddress[17];
    size_t radAddress_len;
    long radPortAuth;
    long radPortAcct;
    long radQueueCount;
    long radFailCount;
    long radAuthSent;
    long radAuthLost;
    long radAcctSent;
    long radAcctLost;
    long radInterSent;
    long radInterLost;
    long radAuthLost1m;
    long radAuthLost5m;
    long radAcctLost1m;
    long radAcctLost5m;
    long radInterLost1m;
    long radInterLost5m;
    long radAuthTime1m;
    long radAuthTime5m;
    long radAcctTime1m;
    long radAcctTime5m;
    long radInterTime1m;
    long radInterTime5m;

    /* Illustrate using a simple linked list */
    int   valid;
    struct radiusStatsTable_entry *next;
};

struct radiusStatsTable_entry  *radiusStatsTable_head;


/* set up linked list from radius module reported statistics */
int
radiusStatsTable_load( netsnmp_cache *cache, void *vmagic ) {
    struct radiusStatsTable_entry *this;
    struct rad_server_stat_t *s;
    LIST_HEAD(stats);
    char addr[17];

    if (rad_server_stats(&stats)) {
        return -1;
    }
    while (!list_empty(&stats)) {
        s = list_entry(stats.next, typeof(*s), entry);
        list_del(&s->entry);

        this = SNMP_MALLOC_TYPEDEF( struct radiusStatsTable_entry );

        this->radID_len = snprintf(this->radID, sizeof(this->radID), "%d", s->id);
        u_inet_ntoa(s->addr, addr);
        strncpy(this->radAddress, addr, sizeof(this->radAddress));
        this->radAddress_len = strlen(addr);
        this->radPortAuth = s->auth_port;
        this->radPortAcct = s->acct_port;

        this->radQueueCount = s->queue_cnt;
        this->radFailCount = s->stat_fail_cnt;

        this->radAuthSent = s->stat_auth_sent;
        this->radAcctSent = s->stat_acct_sent;
        this->radInterSent = s->stat_interim_sent;
        this->radAuthLost = s->stat_auth_lost;
        this->radAcctLost = s->stat_acct_lost;
        this->radInterLost = s->stat_interim_lost;
        this->radAuthLost1m = s->stat_auth_lost_1m;
        this->radAcctLost1m = s->stat_acct_lost_1m;
        this->radInterLost1m = s->stat_interim_lost_1m;
        this->radAuthLost5m = s->stat_auth_lost_5m;
        this->radAcctLost5m = s->stat_acct_lost_5m;
        this->radInterLost5m = s->stat_interim_lost_5m;

        this->radAuthTime1m = s->stat_auth_query_1m;
        this->radAcctTime1m = s->stat_acct_query_1m;
        this->radInterTime1m = s->stat_interim_query_1m;
        this->radAuthTime5m = s->stat_auth_query_5m;
        this->radAcctTime5m = s->stat_acct_query_5m;
        this->radInterTime5m = s->stat_interim_query_5m;

        _free(s);

        this->next = radiusStatsTable_head;
        radiusStatsTable_head = this;    /* Iterate helper is fine with unordered lists! */
    }
    return 0;  /* OK */
}

void
radiusStatsTable_free( netsnmp_cache *cache, void *vmagic ) {
    struct radiusStatsTable_entry *this, *that;

    for ( this = radiusStatsTable_head; this; this=that ) {
        that = this->next;
        SNMP_FREE( this );
    }
    radiusStatsTable_head = NULL;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
radiusStatsTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = radiusStatsTable_head;
    return radiusStatsTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
radiusStatsTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct radiusStatsTable_entry *entry = (struct radiusStatsTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, entry->radID, sizeof(entry->radID) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the radiusStatsTable table */
int
radiusStatsTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct radiusStatsTable_entry          *table_entry;

    DEBUGMSGTL(("radiusStatsTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct radiusStatsTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_RADID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->radID,
                                          table_entry->radID_len);
                break;
            case COLUMN_RADADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->radAddress,
                                          table_entry->radAddress_len);
                break;
            case COLUMN_RADPORTAUTH:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radPortAuth);
                break;
            case COLUMN_RADPORTACCT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radPortAcct);
                break;
            case COLUMN_RADQUEUECOUNT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radQueueCount);
                break;
            case COLUMN_RADFAILCOUNT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radFailCount);
                break;
            case COLUMN_RADAUTHSENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthSent);
                break;
            case COLUMN_RADAUTHLOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthLost);
                break;
            case COLUMN_RADACCTSENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctSent);
                break;
            case COLUMN_RADACCTLOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctLost);
                break;
            case COLUMN_RADINTERSENT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterSent);
                break;
            case COLUMN_RADINTERLOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterLost);
                break;
            case COLUMN_RADAUTHLOST1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthLost1m);
                break;
            case COLUMN_RADAUTHLOST5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthLost5m);
                break;
            case COLUMN_RADACCTLOST1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctLost1m);
                break;
            case COLUMN_RADACCTLOST5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctLost5m);
                break;
            case COLUMN_RADINTERLOST1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterLost1m);
                break;
            case COLUMN_RADINTERLOST5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterLost5m);
                break;
            case COLUMN_RADAUTHTIME1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthTime1m);
                break;
            case COLUMN_RADAUTHTIME5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAuthTime5m);
                break;
            case COLUMN_RADACCTTIME1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctTime1m);
                break;
            case COLUMN_RADACCTTIME5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radAcctTime5m);
                break;
            case COLUMN_RADINTERTIME1M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterTime1m);
                break;
            case COLUMN_RADINTERTIME5M:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->radInterTime5m);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}

#endif /* RADIUS */
